manifest:
  remotes:
   - name: zmkfirmware
     url-base: https://github.com/zmkfirmware
   - name: felixm12138
     url-base: https://github.com/felixm12138
  projects:
   - name: zmk
     remote: zmkfirmware
     revision: main
     import: app/west.yml
   - name: zmk-analog-input-driver
     remote: felixm12138
     revision: main
  self:
    path: config
